backend:
  commit_message:
    create: Create {{ collection }} "{{ slug }}"
    update: Update {{ collection }} "{{ slug }}"
    delete: Delete {{ collection }} "{{ slug }}"
    uploadMedia: Upload "{{ path }}"
    deleteMedia: Delete "{{ path }}"
    openAuthoring: "{{ author-name }}"
  name: git-gateway
  repo: spncrf/home-galleria
  branch: main
  squash_merges: true
  #open_authoring: true # set true for editorial_workflow

editor:
  preview: false

publish_mode: simple  # simple or editorial_workflow
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: artwork
    label: Artwork
    folder: src/content/artwork
    create: true
    fields:
      - { name: title, label: Title, widget: text, required: false }
      - { name: description, label: Description, widget: text, required: false }
      - { name: image, label: Image, widget: image }
      - { name: work_type, label: 'Type of Artwork', widget: select, options: ['Mural', 'Clock']}