backend:
  commit_message:
    create: 'CMS: Create {{ collection }} "{{ slug }}"'
    update: 'CMS: Update {{ collection }} "{{ slug }}"'
    delete: 'CMS: Delete {{ collection }} "{{ slug }}"'
    uploadMedia: 'CMS: Upload "{{ path }}"'
    deleteMedia: 'CMS: Delete "{{ path }}"'
    openAuthoring: "{{ author-name }}"
  name: git-gateway
  repo: spncrf/home-galleria
  branch: main
  squash_merges: true
  #open_authoring: true # set true for editorial_workflow

editor:
  preview: false

publish_mode: simple  # simple or editorial_workflow
media_folder: "public/assets/images"
public_folder: "public/assets/images"

collections:
  - name: home_page
    label: 'Home'
    delete: false
    files:
      - name: 'home_page_content'
        label: 'Home Page Content'
        file: 'src/content/home_page_content.json'
        description: 'Content for the Home Page'
        fields:
          - name: 'about'
            label: About
            widget: markdown
          - name: 'cover'
            label: Cover Photo
            widget: image
            choose_url: false
            
    
  # - name: artwork
  #   label: Artwork
  #   folder: src/content/artwork
  #   create: true
  #   fields:
  #     - { name: title, label: Title, widget: text, required: false }
  #     - { name: description, label: Description, widget: text, required: false }
  #     - { name: image, label: Image, widget: image }
  #     - { name: work_type, label: 'Type of Artwork', widget: select, options: ['Mural', 'Clock']}