backend:
  commit_message:
    create: '{{ author-name }}: Create {{ collection }} "{{ slug }}"'
    update: '{{ author-name }}: Update {{ collection }} "{{ slug }}"'
    delete: '{{ author-name }}: Delete {{ collection }} "{{ slug }}"'
    uploadMedia: '{{ author-name }}: Upload "{{ path }}"'
    deleteMedia: '{{ author-name }}: Delete "{{ path }}"'
  name: git-gateway
  repo: spncrf/home-galleria
  branch: main
  squash_merges: true
  #open_authoring: true # set true for editorial_workflow

editor:
  preview: false

publish_mode: simple  # simple or editorial_workflow
media_folder: "public/assets/images"
public_folder: "assets/images"

collections:
  - name: home_page
    label: 'Home'
    delete: false
    files:
      - name: 'home_content'
        label: 'Home Page Content'
        file: 'src/content/home/content.json'
        description: 'Content for the Home Page'
        fields:
          - name: about
            label: 'About'
            widget: markdown
          - name: tile_link_images
            label: 'Tile Link Images'
            widget: object
            fields:
              - name: mural
                label: 'Mural Image'
                widget: image
                choose_url: false
              - name: clocks
                label: 'Clocks Image'
                widget: image
                choose_url: false
            
    
  # - name: artwork
  #   label: Artwork
  #   folder: src/content/artwork
  #   create: true
  #   fields:
  #     - { name: title, label: Title, widget: text, required: false }
  #     - { name: description, label: Description, widget: text, required: false }
  #     - { name: image, label: Image, widget: image }
  #     - { name: work_type, label: 'Type of Artwork', widget: select, options: ['Mural', 'Clock']}