backend:
  commit_message:
    create: Create {{ collection }} "{{ slug }}"
    update: Update {{ collection }} "{{ slug }}"
    delete: Delete {{ collection }} "{{ slug }}"
    uploadMedia: Upload "{{ path }}"
    deleteMedia: Delete "{{ path }}"
    openAuthoring: "{{ author-name }}"
  name: github
  name: git-gateway
  repo: spncrf/home-galleria
  branch: main
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: mural
    label: Murals
    folder: src/content/murals
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: date }
      - { label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false}