backend:
  commit_message:
    create: '{{ author-name }}: Create {{ collection }} "{{ slug }}"'
    update: '{{ author-name }}: Update {{ collection }} "{{ slug }}"'
    delete: '{{ author-name }}: Delete {{ collection }} "{{ slug }}"'
    uploadMedia: '{{ author-name }}: Upload "{{ path }}"'
    deleteMedia: '{{ author-name }}: Delete "{{ path }}"'
  name: git-gateway
  repo: spncrf/home-galleria
  branch: main
  squash_merges: true
  #open_authoring: true # set true for editorial_workflow

editor:
  preview: false

publish_mode: simple  # simple or editorial_workflow
media_folder: "src/images"
public_folder: "images"

collections:
  - name: home
    label: 'Home'
    delete: false
    files:
      - name: 'data'
        label: 'Home Page Data'
        file: 'src/content/home/data.json'
        description: 'Content for the Home Page'
        fields:
          - name: intro
            label: 'Intro'
            widget: text
          - name: gallery_links
            label: 'Gallery Links'
            widget: object
            fields:
              - name: mural
                label: 'Mural Image'
                widget: image
                choose_url: false
              - name: clock
                label: 'Clock Image'
                widget: image
                choose_url: false
  - name: galleries
    label: 'Galleries'
    delete: false
    files:
      - name: mural
        label: 'Mural Gallery'
        file: src/content/galleries/mural.json
        description: 'Gallery for the Murals'
        fields:
          - name: intro
            label: Intro
            widget: text
          - name: gallery
            label: Gallery
            widget: list
            summary: '{{ fields.image }}'
            allow_add: true
            label_singular: 'Entry'
            fields: 
              - name: image
                label: Image
                widget: image
                choose_url: false
              - name: description
                label: Description
                widget: text
                optional: true
      - name: clock
        label: 'Clock Gallery'
        file: src/content/galleries/clock.json
        description: 'Gallery for the Clocks'
        fields:
          - name: intro
            label: Intro
            widget: text
          - name: gallery
            label: Gallery
            widget: list
            summary: '{{ fields.image }}'
            allow_add: true
            label_singular: 'Entry'
            fields: 
              - name: image
                label: Image
                widget: image
                choose_url: false
              - name: description
                label: Description
                widget: text
                optional: true
  - name: about
    label: About
    delete: false
    files:
      - name: 'data'
        label: 'About Page Data'
        file: 'src/content/home/data.json'
        description: 'Content for the About Page'
        fields:
          - name: page_title
            label: 'About'
            widget: string
          - name: intro
            label: 'Intro'
            widget: markdown


    
  # - name: artwork
  #   label: Artwork
  #   folder: src/content/artwork
  #   create: true
  #   fields:
  #     - { name: title, label: Title, widget: text, required: false }
  #     - { name: description, label: Description, widget: text, required: false }
  #     - { name: image, label: Image, widget: image }
  #     - { name: work_type, label: 'Type of Artwork', widget: select, options: ['Mural', 'Clock']}